Repository VeryGoodOpenSource/very_good_core, pull requests merged in 2022-10, with the labels that each got.

#181 feat: upgrade to Flutter 3.3.3
  .github/workflows/very_good_core.yaml
  src/my_app/.github/workflows/main.yaml
  src/my_app/pubspec.lock
  src/my_app/pubspec.yaml
Labels: enhancement

#183 chore: v0.1.3
  brick/CHANGELOG.md
  brick/brick.yaml
Labels: chore

#191 feat: upgrade to Flutter 3.3.6
  .github/workflows/very_good_core.yaml
  src/my_app/.github/workflows/main.yaml
  src/my_app/ios/Flutter/AppFrameworkInfo.plist
  src/my_app/pubspec.lock
  src/my_app/pubspec.yaml
Labels: enhancement

#193 fix: Add support for GlobalCupertinoLocalizations
  src/my_app/lib/app/view/app.dart
  src/my_app/test/helpers/pump_app.dart
Labels: bug

#196 chore: v0.1.5
  brick/CHANGELOG.md
  brick/brick.yaml
Labels: chore
